M48
; DRILL file {KiCad 9.0.0} date 2025-03-07T15:22:27-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-07T15:22:27-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,Plated,1,4,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X135.25Y-71.12
X137.79Y-71.12
T2
X135.25Y-67.31
X137.79Y-67.31
M30
